output_queue_size: 1
cloud_filter_chain:
  - name: PassThroughFilter
    type: point_cloud2_filters/PassThroughFilterPointCloud2
    params:
      keep_organized: True
      reference_frame: "D435_camera_link"
      x_limits: [0, 1]
      y_limits: [0, 0.4]
      z_limits: [-1, 0.8]
      final_reference_frame: "D435_camera_depth_optical_frame"
  - name: CropBoxFilter
    type: point_cloud2_filters/CropBoxFilterPointCloud2
    params:
      keep_organized: True
      input_frame: "D435_camera_link"
      min_x: 0
      max_x: 1
      min_y: 0
      max_y: 0.4
      min_z: -1
      max_z: 0.8
      output_frame: "D435_camera_depth_optical_frame"
